version: '3'
services:
  app:
    build: .

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
  web:
    build: web/.
    ports:
      - "80:80"