name: A workflow for napier group 26s app
on: push

jobs:
  build:
    name: Group 26 Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge group26
          docker pull mongo
          docker run -d --name mongo-dbserver --network group26 mongo
      - name: Build
        run: docker build -t group_26 .
      - name: Run image
        run: docker run --network group26 --name semgacontainer group_26
      - name: view logs
        run: docker logs semgacontainer
